### PR TITLE
use standard

### PR DESCRIPTION
**Pull request by Shri077**
lets add the missing snippet code and will test it ....

### CODE REVIEW

**Comment by rom1504** [comment]
We're already using standard.
It seems something went wrong in your git setup

**Review by wvffle — APPROVED** [review]
Github diff clearly shows that the code was not linted. LGTM

**Comment by DeltaEvo** [comment]
> Github diff clearly shows that the code was not linted. LGTM

Yes but github show this diff because it's the diff between the parent commit and the commit, the parent commit is https://github.com/PrismarineJS/node-minecraft-wrap/commit/ebb570495360d68cfbe6c7a02d5c754f6f351f53 the commit message is ` Release 0.6.0 ` so it's a very old commit
And it's also weird that the commit author is @rom1504

**Comment by wvffle** [comment]
Didn't catch that

**Pull request closed without merging**
