### PR TITLE
Add bedrock server download support

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
could you also add it to the cli ?

**Comment by u9g** [comment]
> could you also add it to the cli ?

done

**Comment by rom1504** [comment]
could you also add a test ? like https://github.com/PrismarineJS/node-minecraft-wrap/blob/master/test/wrap_server.js (but I guess only the download part)

**Comment by rom1504** [comment]
would be great to finish it

**Comment by rom1504** [comment]
ok main issue here is there are no tests

the rest looks ok

**Pull request merged**
